name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManager
depend: [ PermissionsEx ]
version: ${project.version}
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin for PermissionsEx
